/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
  caption?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  company?: string;
  quote?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  stars?: number;
  featured?: boolean;
  sortOrder?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BlogCtaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogCta";
};

export type CtaSectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ctaSection";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  defaultBlogCta?: BlogCtaReference;
  defaultCtaSection?: CtaSectionReference;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type GlossaryTermReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "glossaryTerm";
};

export type Callout = {
  _type: "callout";
  type?: "tip" | "warning" | "info";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<
      | {
          href?: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference?:
            BlogPostReference | CaseStudyReference | GlossaryTermReference;
          newTab?: boolean;
          _type: "internalLink";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  categories?: Array<string>;
  primaryCategory?: "News" | "Guides" | "Insights" | "Tutorials";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt?: string;
  video?: string;
  author?: AuthorReference;
  date?: string;
  featured?: boolean;
  relatedPosts?: Array<
    {
      _key: string;
    } & BlogPostReference
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              newTab?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference?:
                BlogPostReference | CaseStudyReference | GlossaryTermReference;
              newTab?: boolean;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & Callout)
    | ({
        _key: string;
      } & BlogCtaInline)
  >;
  ctaOverride?: BlogCtaReference;
  ctaSectionOverride?: CtaSectionReference;
  faqs?: Array<
    {
      _key: string;
    } & BlogFaq
  >;
  seo?: Seo;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  client?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt?: string;
  date?: string;
  featured?: boolean;
  comingSoon?: boolean;
  categories?: Array<string>;
  industries?: Array<string>;
  timeline?: string;
  liveUrl?: string;
  galleryImagesAlt?: string;
  galleryImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  content?: Array<
    | {
        body?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                  }
              >;
              level?: number;
              _type: "block";
              _key: string;
            }
          | ({
              _key: string;
            } & VideoEmbed)
        >;
        maxWidth?:
          | ""
          | "20ch"
          | "30ch"
          | "40ch"
          | "48ch"
          | "60ch"
          | "48rem"
          | "60rem"
          | "100%";
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "richText";
        _key: string;
      }
    | {
        body?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                  }
              >;
              level?: number;
              _type: "block";
              _key: string;
            }
          | ({
              _key: string;
            } & VideoEmbed)
        >;
        maxWidth?:
          | ""
          | "20ch"
          | "30ch"
          | "40ch"
          | "48ch"
          | "60ch"
          | "48rem"
          | "60rem"
          | "100%";
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "richTextLeft";
        _key: string;
      }
    | {
        body?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                  }
              >;
              level?: number;
              _type: "block";
              _key: string;
            }
          | ({
              _key: string;
            } & VideoEmbed)
        >;
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "richTextColumns";
        _key: string;
      }
    | {
        body?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal" | "h2" | "h3" | "h4";
              listItem?: "bullet" | "number";
              markDefs?: Array<
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                  }
              >;
              level?: number;
              _type: "block";
              _key: string;
            }
          | ({
              _key: string;
            } & VideoEmbed)
        >;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        imageAlt?: string;
        transparent?: boolean;
        objectFit?: "cover" | "contain";
        aspectRatio?:
          | ""
          | "auto"
          | "wide"
          | "widescreen"
          | "landscape"
          | "square"
          | "portrait"
          | "tall";
        customAspectRatio?: string;
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "richTextWithImage";
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        imageAlt?: string;
        transparent?: boolean;
        aspectRatio?:
          | ""
          | "auto"
          | "wide"
          | "widescreen"
          | "landscape"
          | "square"
          | "portrait"
          | "tall";
        customAspectRatio?: string;
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "fullWidthImage";
        _key: string;
      }
    | {
        defaultAlt?: string;
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          transparent?: boolean;
          _type: "image";
          _key: string;
        }>;
        aspectRatio?:
          | ""
          | "auto"
          | "wide"
          | "widescreen"
          | "landscape"
          | "square"
          | "portrait"
          | "tall";
        customAspectRatio?: string;
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "imageGrid";
        _key: string;
      }
    | {
        items?: Array<{
          value?: string;
          label?: string;
          _key: string;
        }>;
        sectionSpacing?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingTop?: "none" | "xsmall" | "small" | "main" | "large";
        sectionSpacingBottom?: "none" | "xsmall" | "small" | "main" | "large";
        _type: "stats";
        _key: string;
      }
  >;
  ctaSectionOverride?: CtaSectionReference;
  seo?: Seo;
};

export type GlossaryTerm = {
  _id: string;
  _type: "glossaryTerm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  term?: string;
  slug?: Slug;
  shortDefinition?: string;
  category?: "General" | "Technical" | "Business" | "Design";
  relatedTerms?: Array<
    {
      _key: string;
    } & GlossaryTermReference
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              newTab?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference?:
                BlogPostReference | CaseStudyReference | GlossaryTermReference;
              newTab?: boolean;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & VideoEmbed)
  >;
  ctaSectionOverride?: CtaSectionReference;
};

export type CtaSection = {
  _id: string;
  _type: "ctaSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  text?: string;
  primaryButtonLabel?: string;
  primaryButtonHref?: string;
  secondaryButtonLabel?: string;
  secondaryButtonHref?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt?: string;
  overlayStrength?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BlogFaq = {
  _type: "blogFaq";
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      newTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BlogCtaInline = {
  _type: "blogCtaInline";
  cta?: BlogCtaReference;
};

export type BlogCta = {
  _id: string;
  _type: "blogCta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAlt?: string;
  aspectRatio?: "square" | "landscape" | "portrait";
  linkUrl?: string;
  linkLabel?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoEmbed
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | BlogCtaReference
  | CtaSectionReference
  | SiteSettings
  | Seo
  | BlogPostReference
  | CaseStudyReference
  | GlossaryTermReference
  | Callout
  | AuthorReference
  | BlogPost
  | CaseStudy
  | GlossaryTerm
  | CtaSection
  | Slug
  | BlogFaq
  | BlogCtaInline
  | BlogCta
  | Author
  | Code
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost"] | order(date desc) {  title,  "slug": slug.current,  description,  categories,  primaryCategory,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  "author": author->name,  "authorAvatar": author->avatar,  date,  featured}
export type BLOG_POSTS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  categories: Array<string> | null;
  primaryCategory: "Guides" | "Insights" | "News" | "Tutorials" | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  author: string | null;
  authorAvatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug][0] {  title,  "slug": slug.current,  description,  categories,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  "author": author->name,  "authorAvatar": author->avatar,  video,  date,  _updatedAt,  featured,  body[] {    ...,    _type == "blogCtaInline" => {      ...,      "cta": cta->{  _id,  heading,  body,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  aspectRatio,  linkUrl,  linkLabel}    },    markDefs[] {      ...,      _type == "internalLink" => {        ...,        "target": reference->{          _type,          "slug": slug.current,          "title": coalesce(title, term),          "description": coalesce(description, shortDefinition),          image        }      }    }  },  "ctaOverride": ctaOverride->{  _id,  heading,  body,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  aspectRatio,  linkUrl,  linkLabel},  "ctaSectionOverride": ctaSectionOverride->{  _id,  heading,  text,  primaryButtonLabel,  primaryButtonHref,  secondaryButtonLabel,  secondaryButtonHref,  backgroundImage,  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),  overlayStrength},  faqs[] {    question,    answer  },  "relatedPosts": relatedPosts[]->{    title,    "slug": slug.current,    description,    categories,    image,    "imageAlt": coalesce(imageAlt, image.asset->altText, ""),    "author": author->name,    "authorAvatar": author->avatar,    date,    featured  },  seo {    metaTitle,    metaDescription,    ogTitle,    ogDescription,    ogImage  }}
export type BLOG_POST_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  description: string | null;
  categories: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  author: string | null;
  authorAvatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  video: string | null;
  date: string | null;
  _updatedAt: string;
  featured: boolean | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?:
                BlogPostReference | CaseStudyReference | GlossaryTermReference;
              newTab?: boolean;
              _type: "internalLink";
              _key: string;
              target:
                | {
                    _type: "blogPost";
                    slug: string | null;
                    title: string | null;
                    description: string | null;
                    image: {
                      asset?: SanityImageAssetReference;
                      media?: unknown;
                      hotspot?: SanityImageHotspot;
                      crop?: SanityImageCrop;
                      _type: "image";
                    } | null;
                  }
                | {
                    _type: "caseStudy";
                    slug: string | null;
                    title: string | null;
                    description: string | null;
                    image: {
                      asset?: SanityImageAssetReference;
                      media?: unknown;
                      hotspot?: SanityImageHotspot;
                      crop?: SanityImageCrop;
                      _type: "image";
                    } | null;
                  }
                | {
                    _type: "glossaryTerm";
                    slug: string | null;
                    title: string | null;
                    description: string | null;
                    image: null;
                  }
                | null;
            }
          | {
              href?: string;
              newTab?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "blogCtaInline";
        cta: {
          _id: string;
          heading: string | null;
          body: string | null;
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          imageAlt: string | "";
          aspectRatio: "landscape" | "portrait" | "square" | null;
          linkUrl: string | null;
          linkLabel: string | null;
        } | null;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "callout";
        type?: "info" | "tip" | "warning";
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<
            | {
                reference?:
                  | BlogPostReference
                  | CaseStudyReference
                  | GlossaryTermReference;
                newTab?: boolean;
                _type: "internalLink";
                _key: string;
              }
            | {
                href?: string;
                newTab?: boolean;
                _type: "link";
                _key: string;
              }
          >;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "videoEmbed";
        url?: string;
        caption?: string;
        markDefs: null;
      }
  > | null;
  ctaOverride: {
    _id: string;
    heading: string | null;
    body: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    aspectRatio: "landscape" | "portrait" | "square" | null;
    linkUrl: string | null;
    linkLabel: string | null;
  } | null;
  ctaSectionOverride: {
    _id: string;
    heading: string | null;
    text: string | null;
    primaryButtonLabel: string | null;
    primaryButtonHref: string | null;
    secondaryButtonLabel: string | null;
    secondaryButtonHref: string | null;
    backgroundImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    overlayStrength: number | null;
  } | null;
  faqs: Array<{
    question: string | null;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        newTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  relatedPosts: Array<{
    title: string | null;
    slug: string | null;
    description: string | null;
    categories: Array<string> | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    author: string | null;
    authorAvatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    date: string | null;
    featured: boolean | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_SLUGS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)].slug.current
export type BLOG_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: RELATED_BLOG_POSTS_QUERY
// Query: *[  _type == "blogPost"  && slug.current != $slug  && !(slug.current in $excludeSlugs)  && count(categories[string::lower(@) in $categories]) > 0] | order(date desc) [0...6] {  title,  "slug": slug.current,  description,  categories,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  "author": author->name,  "authorAvatar": author->avatar,  date,  featured}
export type RELATED_BLOG_POSTS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  categories: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  author: string | null;
  authorAvatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "blogPost" && $category in categories] | order(date desc) {  title,  "slug": slug.current,  description,  categories,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  "author": author->name,  "authorAvatar": author->avatar,  date,  featured}
export type BLOG_POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  categories: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  author: string | null;
  authorAvatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_CATEGORIES_QUERY
// Query: array::unique(*[_type == "blogPost"].categories[])
export type BLOG_CATEGORIES_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  "defaultBlogCta": defaultBlogCta->{  _id,  heading,  body,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  aspectRatio,  linkUrl,  linkLabel},  "defaultCtaSection": defaultCtaSection->{  _id,  heading,  text,  primaryButtonLabel,  primaryButtonHref,  secondaryButtonLabel,  secondaryButtonHref,  backgroundImage,  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),  overlayStrength}}
export type SITE_SETTINGS_QUERY_RESULT = {
  defaultBlogCta: {
    _id: string;
    heading: string | null;
    body: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    aspectRatio: "landscape" | "portrait" | "square" | null;
    linkUrl: string | null;
    linkLabel: string | null;
  } | null;
  defaultCtaSection: {
    _id: string;
    heading: string | null;
    text: string | null;
    primaryButtonLabel: string | null;
    primaryButtonHref: string | null;
    secondaryButtonLabel: string | null;
    secondaryButtonHref: string | null;
    backgroundImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    overlayStrength: number | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy"] | order(date desc) {  title,  "slug": slug.current,  description,  client,  categories,  industries,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  date,  featured,  comingSoon,  liveUrl}
export type CASE_STUDIES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  client: string | null;
  categories: Array<string> | null;
  industries: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  date: string | null;
  featured: boolean | null;
  comingSoon: boolean | null;
  liveUrl: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0] {  title,  "slug": slug.current,  description,  client,  categories,  industries,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  date,  _updatedAt,  featured,  comingSoon,  timeline,  liveUrl,  galleryImagesAlt,  galleryImages[] {    asset,    hotspot,    crop,    "alt": coalesce(alt, ^.galleryImagesAlt, asset->altText, "")  },  content[] {    _type,    _key,    // per-block vertical spacing (drives Section paddingTop/paddingBottom)    sectionSpacing,    sectionSpacingTop,    sectionSpacingBottom,    // richText, richTextLeft — editor-set content width    maxWidth,    // richText, richTextColumns    body[] {      ...,      markDefs[] {        ...,        _type == "internalLink" => {          ...,          "target": reference->{ _type, "slug": slug.current }        }      }    },    // fullWidthImage, richTextWithImage    image,    "imageAlt": coalesce(imageAlt, image.asset->altText, ""),    // image display options (fullWidthImage, richTextWithImage, imageGrid)    aspectRatio,    customAspectRatio,    transparent,    objectFit,    // imageGrid    defaultAlt,    images[] {      asset,      hotspot,      crop,      "alt": coalesce(alt, ^.defaultAlt, asset->altText, ""),      transparent    },    // stats    items[] {      value,      label    }  },  "ctaSectionOverride": ctaSectionOverride->{  _id,  heading,  text,  primaryButtonLabel,  primaryButtonHref,  secondaryButtonLabel,  secondaryButtonHref,  backgroundImage,  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),  overlayStrength},  seo {    metaTitle,    metaDescription,    ogTitle,    ogDescription,    ogImage  }}
export type CASE_STUDY_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  description: string | null;
  client: string | null;
  categories: Array<string> | null;
  industries: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  date: string | null;
  _updatedAt: string;
  featured: boolean | null;
  comingSoon: boolean | null;
  timeline: string | null;
  liveUrl: string | null;
  galleryImagesAlt: string | null;
  galleryImages: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | "";
  }> | null;
  content: Array<
    | {
        _type: "fullWidthImage";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth: null;
        body: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        imageAlt: string | "";
        aspectRatio:
          | ""
          | "auto"
          | "landscape"
          | "portrait"
          | "square"
          | "tall"
          | "wide"
          | "widescreen"
          | null;
        customAspectRatio: string | null;
        transparent: boolean | null;
        objectFit: null;
        defaultAlt: null;
        images: null;
        items: null;
      }
    | {
        _type: "imageGrid";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth: null;
        body: null;
        image: null;
        imageAlt: "";
        aspectRatio:
          | ""
          | "auto"
          | "landscape"
          | "portrait"
          | "square"
          | "tall"
          | "wide"
          | "widescreen"
          | null;
        customAspectRatio: string | null;
        transparent: null;
        objectFit: null;
        defaultAlt: string | null;
        images: Array<{
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | "";
          transparent: boolean | null;
        }> | null;
        items: null;
      }
    | {
        _type: "richText";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth:
          | ""
          | "100%"
          | "20ch"
          | "30ch"
          | "40ch"
          | "48ch"
          | "48rem"
          | "60ch"
          | "60rem"
          | null;
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet" | "number";
              markDefs: Array<
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                    target:
                      | {
                          _type: "blogPost";
                          slug: string | null;
                        }
                      | {
                          _type: "caseStudy";
                          slug: string | null;
                        }
                      | {
                          _type: "glossaryTerm";
                          slug: string | null;
                        }
                      | null;
                  }
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
              > | null;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              _key: string;
              _type: "videoEmbed";
              url?: string;
              caption?: string;
              markDefs: null;
            }
        > | null;
        image: null;
        imageAlt: "";
        aspectRatio: null;
        customAspectRatio: null;
        transparent: null;
        objectFit: null;
        defaultAlt: null;
        images: null;
        items: null;
      }
    | {
        _type: "richTextColumns";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth: null;
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet" | "number";
              markDefs: Array<
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                    target:
                      | {
                          _type: "blogPost";
                          slug: string | null;
                        }
                      | {
                          _type: "caseStudy";
                          slug: string | null;
                        }
                      | {
                          _type: "glossaryTerm";
                          slug: string | null;
                        }
                      | null;
                  }
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
              > | null;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              _key: string;
              _type: "videoEmbed";
              url?: string;
              caption?: string;
              markDefs: null;
            }
        > | null;
        image: null;
        imageAlt: "";
        aspectRatio: null;
        customAspectRatio: null;
        transparent: null;
        objectFit: null;
        defaultAlt: null;
        images: null;
        items: null;
      }
    | {
        _type: "richTextLeft";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth:
          | ""
          | "100%"
          | "20ch"
          | "30ch"
          | "40ch"
          | "48ch"
          | "48rem"
          | "60ch"
          | "60rem"
          | null;
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet" | "number";
              markDefs: Array<
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                    target:
                      | {
                          _type: "blogPost";
                          slug: string | null;
                        }
                      | {
                          _type: "caseStudy";
                          slug: string | null;
                        }
                      | {
                          _type: "glossaryTerm";
                          slug: string | null;
                        }
                      | null;
                  }
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
              > | null;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              _key: string;
              _type: "videoEmbed";
              url?: string;
              caption?: string;
              markDefs: null;
            }
        > | null;
        image: null;
        imageAlt: "";
        aspectRatio: null;
        customAspectRatio: null;
        transparent: null;
        objectFit: null;
        defaultAlt: null;
        images: null;
        items: null;
      }
    | {
        _type: "richTextWithImage";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth: null;
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet" | "number";
              markDefs: Array<
                | {
                    reference?:
                      | BlogPostReference
                      | CaseStudyReference
                      | GlossaryTermReference;
                    newTab?: boolean;
                    _type: "internalLink";
                    _key: string;
                    target:
                      | {
                          _type: "blogPost";
                          slug: string | null;
                        }
                      | {
                          _type: "caseStudy";
                          slug: string | null;
                        }
                      | {
                          _type: "glossaryTerm";
                          slug: string | null;
                        }
                      | null;
                  }
                | {
                    href?: string;
                    newTab?: boolean;
                    _type: "link";
                    _key: string;
                  }
              > | null;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              _key: string;
              _type: "videoEmbed";
              url?: string;
              caption?: string;
              markDefs: null;
            }
        > | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        imageAlt: string | "";
        aspectRatio:
          | ""
          | "auto"
          | "landscape"
          | "portrait"
          | "square"
          | "tall"
          | "wide"
          | "widescreen"
          | null;
        customAspectRatio: string | null;
        transparent: boolean | null;
        objectFit: "contain" | "cover" | null;
        defaultAlt: null;
        images: null;
        items: null;
      }
    | {
        _type: "stats";
        _key: string;
        sectionSpacing: "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingTop:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        sectionSpacingBottom:
          "large" | "main" | "none" | "small" | "xsmall" | null;
        maxWidth: null;
        body: null;
        image: null;
        imageAlt: "";
        aspectRatio: null;
        customAspectRatio: null;
        transparent: null;
        objectFit: null;
        defaultAlt: null;
        images: null;
        items: Array<{
          value: string | null;
          label: string | null;
        }> | null;
      }
  > | null;
  ctaSectionOverride: {
    _id: string;
    heading: string | null;
    text: string | null;
    primaryButtonLabel: string | null;
    primaryButtonHref: string | null;
    secondaryButtonLabel: string | null;
    secondaryButtonHref: string | null;
    backgroundImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    overlayStrength: number | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogTitle: string | null;
    ogDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current) && comingSoon != true].slug.current
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: RELATED_CASE_STUDIES_QUERY
// Query: *[  _type == "caseStudy"  && slug.current != $slug  && defined(image.asset)] | order(date desc) [0...4] {  title,  "slug": slug.current,  description,  client,  categories,  industries,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),  date,  featured,  comingSoon,  liveUrl}
export type RELATED_CASE_STUDIES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  client: string | null;
  categories: Array<string> | null;
  industries: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
  date: string | null;
  featured: boolean | null;
  comingSoon: boolean | null;
  liveUrl: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: GLOSSARY_TERMS_QUERY
// Query: *[_type == "glossaryTerm"] | order(term asc) {  term,  "slug": slug.current,  shortDefinition,  category,  "relatedTerms": relatedTerms[]->slug.current}
export type GLOSSARY_TERMS_QUERY_RESULT = Array<{
  term: string | null;
  slug: string | null;
  shortDefinition: string | null;
  category: "Business" | "Design" | "General" | "Technical" | null;
  relatedTerms: Array<string | null> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: GLOSSARY_TERM_QUERY
// Query: *[_type == "glossaryTerm" && slug.current == $slug][0] {  term,  "slug": slug.current,  shortDefinition,  category,  _createdAt,  _updatedAt,  "relatedTerms": relatedTerms[]->{    term,    "slug": slug.current,    shortDefinition,    category  },  body[] {    ...,    markDefs[] {      ...,      _type == "internalLink" => {        ...,        "target": reference->{          _type,          "slug": slug.current,          "title": coalesce(title, term),          "description": coalesce(description, shortDefinition),          image        }      }    }  },  "ctaSectionOverride": ctaSectionOverride->{  _id,  heading,  text,  primaryButtonLabel,  primaryButtonHref,  secondaryButtonLabel,  secondaryButtonHref,  backgroundImage,  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),  overlayStrength}}
export type GLOSSARY_TERM_QUERY_RESULT = {
  term: string | null;
  slug: string | null;
  shortDefinition: string | null;
  category: "Business" | "Design" | "General" | "Technical" | null;
  _createdAt: string;
  _updatedAt: string;
  relatedTerms: Array<{
    term: string | null;
    slug: string | null;
    shortDefinition: string | null;
    category: "Business" | "Design" | "General" | "Technical" | null;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?:
                BlogPostReference | CaseStudyReference | GlossaryTermReference;
              newTab?: boolean;
              _type: "internalLink";
              _key: string;
              target:
                | {
                    _type: "blogPost";
                    slug: string | null;
                    title: string | null;
                    description: string | null;
                    image: {
                      asset?: SanityImageAssetReference;
                      media?: unknown;
                      hotspot?: SanityImageHotspot;
                      crop?: SanityImageCrop;
                      _type: "image";
                    } | null;
                  }
                | {
                    _type: "caseStudy";
                    slug: string | null;
                    title: string | null;
                    description: string | null;
                    image: {
                      asset?: SanityImageAssetReference;
                      media?: unknown;
                      hotspot?: SanityImageHotspot;
                      crop?: SanityImageCrop;
                      _type: "image";
                    } | null;
                  }
                | {
                    _type: "glossaryTerm";
                    slug: string | null;
                    title: string | null;
                    description: string | null;
                    image: null;
                  }
                | null;
            }
          | {
              href?: string;
              newTab?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "videoEmbed";
        url?: string;
        caption?: string;
        markDefs: null;
      }
  > | null;
  ctaSectionOverride: {
    _id: string;
    heading: string | null;
    text: string | null;
    primaryButtonLabel: string | null;
    primaryButtonHref: string | null;
    secondaryButtonLabel: string | null;
    secondaryButtonHref: string | null;
    backgroundImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | "";
    overlayStrength: number | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: GLOSSARY_SLUGS_QUERY
// Query: *[_type == "glossaryTerm" && defined(slug.current)].slug.current
export type GLOSSARY_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(sortOrder asc) {  _id,  name,  role,  company,  quote,  avatar,  website,  stars,  featured,  sortOrder}
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  company: string | null;
  quote: string | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  website: string | null;
  stars: number | null;
  featured: boolean | null;
  sortOrder: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(sortOrder asc) {  _id,  name,  role,  company,  quote,  avatar,  website,  stars,  featured,  sortOrder}
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  company: string | null;
  quote: string | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  website: string | null;
  stars: number | null;
  featured: true;
  sortOrder: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy" && slug.current in $slugs] {  "slug": slug.current,  client,  description,  image,  "imageAlt": coalesce(imageAlt, image.asset->altText, "")}
export type FEATURED_CASE_STUDIES_QUERY_RESULT = Array<{
  slug: string | null;
  client: string | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAlt: string | "";
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "blogPost"] | order(date desc) {\n  title,\n  "slug": slug.current,\n  description,\n  categories,\n  primaryCategory,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  "author": author->name,\n  "authorAvatar": author->avatar,\n  date,\n  featured\n}': BLOG_POSTS_QUERY_RESULT;
    '*[_type == "blogPost" && slug.current == $slug][0] {\n  title,\n  "slug": slug.current,\n  description,\n  categories,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  "author": author->name,\n  "authorAvatar": author->avatar,\n  video,\n  date,\n  _updatedAt,\n  featured,\n  body[] {\n    ...,\n    _type == "blogCtaInline" => {\n      ...,\n      "cta": cta->{\n  _id,\n  heading,\n  body,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  aspectRatio,\n  linkUrl,\n  linkLabel\n}\n    },\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        ...,\n        "target": reference->{\n          _type,\n          "slug": slug.current,\n          "title": coalesce(title, term),\n          "description": coalesce(description, shortDefinition),\n          image\n        }\n      }\n    }\n  },\n  "ctaOverride": ctaOverride->{\n  _id,\n  heading,\n  body,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  aspectRatio,\n  linkUrl,\n  linkLabel\n},\n  "ctaSectionOverride": ctaSectionOverride->{\n  _id,\n  heading,\n  text,\n  primaryButtonLabel,\n  primaryButtonHref,\n  secondaryButtonLabel,\n  secondaryButtonHref,\n  backgroundImage,\n  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),\n  overlayStrength\n},\n  faqs[] {\n    question,\n    answer\n  },\n  "relatedPosts": relatedPosts[]->{\n    title,\n    "slug": slug.current,\n    description,\n    categories,\n    image,\n    "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n    "author": author->name,\n    "authorAvatar": author->avatar,\n    date,\n    featured\n  },\n  seo {\n    metaTitle,\n    metaDescription,\n    ogTitle,\n    ogDescription,\n    ogImage\n  }\n}': BLOG_POST_QUERY_RESULT;
    '*[_type == "blogPost" && defined(slug.current)].slug.current': BLOG_SLUGS_QUERY_RESULT;
    '*[\n  _type == "blogPost"\n  && slug.current != $slug\n  && !(slug.current in $excludeSlugs)\n  && count(categories[string::lower(@) in $categories]) > 0\n] | order(date desc) [0...6] {\n  title,\n  "slug": slug.current,\n  description,\n  categories,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  "author": author->name,\n  "authorAvatar": author->avatar,\n  date,\n  featured\n}': RELATED_BLOG_POSTS_QUERY_RESULT;
    '*[_type == "blogPost" && $category in categories] | order(date desc) {\n  title,\n  "slug": slug.current,\n  description,\n  categories,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  "author": author->name,\n  "authorAvatar": author->avatar,\n  date,\n  featured\n}': BLOG_POSTS_BY_CATEGORY_QUERY_RESULT;
    'array::unique(*[_type == "blogPost"].categories[])': BLOG_CATEGORIES_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  "defaultBlogCta": defaultBlogCta->{\n  _id,\n  heading,\n  body,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  aspectRatio,\n  linkUrl,\n  linkLabel\n},\n  "defaultCtaSection": defaultCtaSection->{\n  _id,\n  heading,\n  text,\n  primaryButtonLabel,\n  primaryButtonHref,\n  secondaryButtonLabel,\n  secondaryButtonHref,\n  backgroundImage,\n  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),\n  overlayStrength\n}\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "caseStudy"] | order(date desc) {\n  title,\n  "slug": slug.current,\n  description,\n  client,\n  categories,\n  industries,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  date,\n  featured,\n  comingSoon,\n  liveUrl\n}': CASE_STUDIES_QUERY_RESULT;
    '*[_type == "caseStudy" && slug.current == $slug][0] {\n  title,\n  "slug": slug.current,\n  description,\n  client,\n  categories,\n  industries,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  date,\n  _updatedAt,\n  featured,\n  comingSoon,\n  timeline,\n  liveUrl,\n  galleryImagesAlt,\n  galleryImages[] {\n    asset,\n    hotspot,\n    crop,\n    "alt": coalesce(alt, ^.galleryImagesAlt, asset->altText, "")\n  },\n  content[] {\n    _type,\n    _key,\n    // per-block vertical spacing (drives Section paddingTop/paddingBottom)\n    sectionSpacing,\n    sectionSpacingTop,\n    sectionSpacingBottom,\n    // richText, richTextLeft \u2014 editor-set content width\n    maxWidth,\n    // richText, richTextColumns\n    body[] {\n      ...,\n      markDefs[] {\n        ...,\n        _type == "internalLink" => {\n          ...,\n          "target": reference->{ _type, "slug": slug.current }\n        }\n      }\n    },\n    // fullWidthImage, richTextWithImage\n    image,\n    "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n    // image display options (fullWidthImage, richTextWithImage, imageGrid)\n    aspectRatio,\n    customAspectRatio,\n    transparent,\n    objectFit,\n    // imageGrid\n    defaultAlt,\n    images[] {\n      asset,\n      hotspot,\n      crop,\n      "alt": coalesce(alt, ^.defaultAlt, asset->altText, ""),\n      transparent\n    },\n    // stats\n    items[] {\n      value,\n      label\n    }\n  },\n  "ctaSectionOverride": ctaSectionOverride->{\n  _id,\n  heading,\n  text,\n  primaryButtonLabel,\n  primaryButtonHref,\n  secondaryButtonLabel,\n  secondaryButtonHref,\n  backgroundImage,\n  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),\n  overlayStrength\n},\n  seo {\n    metaTitle,\n    metaDescription,\n    ogTitle,\n    ogDescription,\n    ogImage\n  }\n}': CASE_STUDY_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current) && comingSoon != true].slug.current': CASE_STUDY_SLUGS_QUERY_RESULT;
    '*[\n  _type == "caseStudy"\n  && slug.current != $slug\n  && defined(image.asset)\n] | order(date desc) [0...4] {\n  title,\n  "slug": slug.current,\n  description,\n  client,\n  categories,\n  industries,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, ""),\n  date,\n  featured,\n  comingSoon,\n  liveUrl\n}': RELATED_CASE_STUDIES_QUERY_RESULT;
    '*[_type == "glossaryTerm"] | order(term asc) {\n  term,\n  "slug": slug.current,\n  shortDefinition,\n  category,\n  "relatedTerms": relatedTerms[]->slug.current\n}': GLOSSARY_TERMS_QUERY_RESULT;
    '*[_type == "glossaryTerm" && slug.current == $slug][0] {\n  term,\n  "slug": slug.current,\n  shortDefinition,\n  category,\n  _createdAt,\n  _updatedAt,\n  "relatedTerms": relatedTerms[]->{\n    term,\n    "slug": slug.current,\n    shortDefinition,\n    category\n  },\n  body[] {\n    ...,\n    markDefs[] {\n      ...,\n      _type == "internalLink" => {\n        ...,\n        "target": reference->{\n          _type,\n          "slug": slug.current,\n          "title": coalesce(title, term),\n          "description": coalesce(description, shortDefinition),\n          image\n        }\n      }\n    }\n  },\n  "ctaSectionOverride": ctaSectionOverride->{\n  _id,\n  heading,\n  text,\n  primaryButtonLabel,\n  primaryButtonHref,\n  secondaryButtonLabel,\n  secondaryButtonHref,\n  backgroundImage,\n  "imageAlt": coalesce(imageAlt, backgroundImage.asset->altText, ""),\n  overlayStrength\n}\n}': GLOSSARY_TERM_QUERY_RESULT;
    '*[_type == "glossaryTerm" && defined(slug.current)].slug.current': GLOSSARY_SLUGS_QUERY_RESULT;
    '*[_type == "testimonial"] | order(sortOrder asc) {\n  _id,\n  name,\n  role,\n  company,\n  quote,\n  avatar,\n  website,\n  stars,\n  featured,\n  sortOrder\n}': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "testimonial" && featured == true] | order(sortOrder asc) {\n  _id,\n  name,\n  role,\n  company,\n  quote,\n  avatar,\n  website,\n  stars,\n  featured,\n  sortOrder\n}': FEATURED_TESTIMONIALS_QUERY_RESULT;
    '*[_type == "caseStudy" && slug.current in $slugs] {\n  "slug": slug.current,\n  client,\n  description,\n  image,\n  "imageAlt": coalesce(imageAlt, image.asset->altText, "")\n}': FEATURED_CASE_STUDIES_QUERY_RESULT;
  }
}
